"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
const nav=[["Home","/"],["About","/about"],["Services","/services"],["Clinical Governance","/governance"],["Founding Team","/team"],["Contact","/contact"]];
export function Header({active}){const[o,setO]=useState(false);return <><div className="top"><div className="shell">Clinician-led • NHS experienced • Patient focused</div></div><nav className="nav" aria-label="Main navigation"><div className="shell navin"><Link className="brand" href="/"><span className="mark" aria-hidden="true">+</span><span>Insight Health<br/>Partners</span></Link><button className="menu" aria-label="Toggle navigation" aria-expanded={o} onClick={()=>setO(!o)}>☰</button><div className={"links "+(o?"open":"")}>{nav.map(([n,h])=><Link className={active===n?"active":""} key={h} href={h}>{n}</Link>)}</div><Link className="btn" href="/contact">Discuss a service</Link></div></nav></>}
export function Footer(){return <footer className="footer"><div className="shell"><div className="footgrid"><div><div className="brand" style={{color:"white"}}><span className="mark">+</span><span>Insight Health Partners Ltd</span></div><p style={{lineHeight:1.7}}>Clinician-led diagnostic, radiology and community healthcare services supporting NHS partners.</p></div><div><strong>Explore</strong><Link href="/about">About us</Link><Link href="/services">Our services</Link><Link href="/governance">Clinical governance</Link></div><div><strong>Connect</strong><Link href="/team">Founding team</Link><Link href="/contact">Contact us</Link><p>CQC registration in progress</p></div></div><div className="legal">© {new Date().getFullYear()} Insight Health Partners Ltd. All rights reserved. This website does not provide medical advice.</div></div></footer>}
export function PageHero({eyebrow,title,children}){return <section className="pagehero"><div className="shell"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{children}</p></div></section>}
export function Reveal(){useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("on")),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>io.observe(x));return()=>io.disconnect()},[]);return null}
export function CTA(){return <section className="section"><div className="shell"><div className="band"><div><h2>Let’s strengthen services together.</h2><p>Talk to our clinician-led team about your diagnostic or community healthcare priorities.</p></div><Link className="btn alt" href="/contact">Start a conversation →</Link></div></div></section>}
