"use client";
import {useState} from "react";
import Link from "next/link";

function PendingNotice(){return <p className="form-notice">Secure online submission is being prepared. Until it is enabled, information entered here is not transmitted. You can contact us using the email address shown on this page.</p>}

export function CareerForm(){const[notice,setNotice]=useState(false);return <form className="form panel" onSubmit={event=>{event.preventDefault();setNotice(true)}}><h3>Register your interest</h3><label>Full name<input name="name" required autoComplete="name"/></label><label>Email address<input name="email" required type="email" autoComplete="email"/></label><label>Professional role<input name="role" required/></label><label>HCPC registration number <span>(optional)</span><input name="hcpc"/></label><label>Areas of interest<select name="interest" defaultValue=""><option value="" disabled>Select an area</option><option>Diagnostic ultrasound</option><option>Community MSK</option><option>Radiology</option><option>Ultrasound-guided procedures</option><option>Service leadership</option><option>Other</option></select></label><label>Attach CV <span>(PDF or Word)</span><input name="cv" type="file" accept=".pdf,.doc,.docx"/></label><label>Short message<textarea name="message"/></label><label className="consent"><input type="checkbox" required/> <span>I have read the <Link href="/privacy">privacy policy</Link> and consent to Insight Health Partners using my details to respond to this expression of interest.</span></label><button className="btn" type="submit">Submit interest</button>{notice&&<PendingNotice/>}<small>Do not include patient information or special-category personal data in your CV or message.</small></form>}

export function ContactForm(){const[notice,setNotice]=useState(false);return <form className="form panel" onSubmit={event=>{event.preventDefault();setNotice(true)}}><h3>Send us a message</h3><label>Full name<input name="name" required autoComplete="name"/></label><label>Work email<input name="email" required type="email" autoComplete="email"/></label><label>Telephone <span>(optional)</span><input name="telephone" type="tel" autoComplete="tel"/></label><label>Organisation<input name="organisation" required autoComplete="organization"/></label><label>Area of interest<select name="interest"><option>Insourcing</option><option>Outsourcing</option><option>Diagnostic ultrasound</option><option>Community MSK services</option><option>Radiology workforce</option><option>Other</option></select></label><label>Message<textarea name="message" required/></label><label className="consent"><input type="checkbox" required/> <span>I have read the <Link href="/privacy">privacy policy</Link> and agree to my information being used to respond to my enquiry.</span></label><button className="btn" type="submit">Send message</button>{notice&&<PendingNotice/>}<small>Please do not send confidential patient information through this form.</small></form>}
