import Image from "next/image";
import Link from "next/link";
import {Header,Footer,Reveal} from "./components";
import {CareerForm,ContactForm} from "./forms";

const team=[
  ["KB","Khaled Barick","Co-Founder"],
  ["GE","Gareth Evans","Co-Founder"],
  ["MP","Mikesh Patel","Co-Founder"],
  ["ML","Maxence Legout","Co-Founder"],
  ["PW","Paul Watson","Advanced Practice Physiotherapist"],
  ["DT","David Toy","Advanced Practice Physiotherapist"]
];

const repository=process.env.GITHUB_REPOSITORY?.split("/")[1]??"";
const pageBase=repository?`/${repository}`:"";

export default function Home(){return <><Header/><main>
  <section className="hero" id="home"><div className="shell hero-grid"><div><h1>Partnering with the NHS to deliver outstanding MSK ultrasound and guided injection services.</h1><p>Insight Health Partners supports NHS Trusts, Integrated Care Boards, GP Federations, Primary Care Networks and Community Diagnostic Centres with focused musculoskeletal diagnostic ultrasound and ultrasound-guided injection capacity.</p><div className="actions"><Link className="btn light" href="/#our-services">Explore our services</Link><Link className="text-link" href="/#get-in-touch">Start a conversation →</Link></div></div><div className="hero-photos" role="group" aria-label="MSK diagnostic ultrasound and guided injection services"><div className="hero-photo-main"><Image src={`${pageBase}/images/ultrasound-diagnostic.jpg`} alt="Clinician operating diagnostic ultrasound equipment" fill priority sizes="(max-width: 940px) 100vw, 25vw"/></div><div className="hero-photo-small"><Image src={`${pageBase}/images/patient-consultation.jpg`} alt="Clinician discussing care with a patient" fill priority sizes="(max-width: 940px) 50vw, 13vw"/></div><div className="hero-photo-small"><Image src={`${pageBase}/images/guided-injection.jpg`} alt="Clinician preparing medication for a guided injection" fill priority sizes="(max-width: 940px) 50vw, 13vw"/></div><div className="hero-photo-copy"><strong>Better access.<br/>Better pathways.<br/>Better care.</strong></div></div></div></section>

  <section className="section anchor-section" id="who-we-are"><div className="shell"><div className="section-no">Who we are</div><div className="heading wide"><h2>Healthcare experience that understands the whole pathway.</h2><p>We are six senior healthcare professionals with more than 80 years of combined NHS experience across musculoskeletal services, radiology, emergency medicine, orthopaedics, rheumatology, primary care and community care.</p></div>
    <div className="team">{team.map(([initials,name,role])=><article className="person reveal" key={name}><div className="portrait" role="img" aria-label={`${name} photograph placeholder`}><span>{initials}</span><small>Photo to follow</small></div><div className="person-copy"><h3>{name}</h3><p>{role}</p><span>Advanced Practice Physiotherapist and qualified musculoskeletal sonographer.</span><div className="professional-status"><span>HCPC registered</span><span>CSP member</span></div><div className="bio-placeholder">Full professional biography to be added.</div></div></article>)}</div>
    <div className="story-grid"><div><div className="section-no">Our story</div><h2>Turning frontline understanding into practical action.</h2></div><div className="prose"><p>We built our careers as Advanced Practice Physiotherapists and leaders in the NHS, working across MSK services, radiology and connected pathways. We have seen first-hand how long waits, fragmented pathways, limited resources and avoidable hand-offs affect patients, teams and the wider system.</p><p>Insight Health Partners began with a shared decision to contribute differently: combining the clinical standards of experienced NHS practitioners with the flexibility to add capacity, remove friction and build services around the people who use them.</p><p>Our role is not simply to fill gaps. We work alongside local teams to understand demand, strengthen governance, develop people and create sustainable pathways that leave services more resilient.</p></div></div>
    <div className="mission"><div><span>Our mission</span><h2>To make high-quality diagnostic and community healthcare easier to access, more efficient to deliver and better connected for every patient.</h2></div></div>
    <div className="grid three"><article className="card"><h3>Our goals</h3><ul className="check"><li>Reduce waiting times and improve access</li><li>Simplify inefficient patient pathways</li><li>Increase safe diagnostic and procedural capacity</li><li>Support and develop the NHS workforce</li><li>Deliver measurable, sustainable improvement</li></ul></article><article className="card"><h3>How we deliver</h3><ul className="check"><li>Flexible evening and weekend services</li><li>Efficient appointment scheduling</li><li>Pathway review to reduce unnecessary steps</li><li>Experienced autonomous practitioners</li><li>Clear outcomes, audit and continuous learning</li></ul></article><article className="card accent-card"><h3>Professional assurance</h3><p>Our team includes HCPC-registered professionals, CSP members, qualified sonographers, independent prescribers and clinicians experienced in ultrasound-guided procedures.</p><p><strong>CQC registration is in preparation.</strong></p></article></div>
  </div></section>

  <section className="section soft anchor-section" id="our-services"><div className="shell"><div className="section-no">Our services</div><div className="heading wide"><h2>MSK diagnostic ultrasound and guided injections, delivered your way.</h2><p>We provide focused musculoskeletal diagnostic ultrasound and ultrasound-guided injection services through insourcing or outsourcing models shaped around local pathways, governance requirements and patient demand.</p></div><div className="delivery-models"><article><span>Insourcing</span><h3>Additional MSK capacity within your service.</h3><p>Our practitioners work within your facilities, using the host organisation’s agreed equipment, systems and pathways to deliver MSK diagnostic ultrasound and ultrasound-guided injections alongside local teams.</p></article><article><span>Outsourcing</span><h3>A managed MSK service on your behalf.</h3><p>We provide the practitioners, our own ultrasound and procedural equipment, clinical leadership, operational delivery and performance assurance for MSK diagnostic ultrasound and ultrasound-guided injections.</p></article></div><article className="transformation-card"><div><span>Service transformation</span><h3>Improving the pathway around the service.</h3><p>We can review referral criteria, appointment design, reporting, guided-injection pathways and workforce deployment to improve access, flow and outcomes.</p></div></article></div></section>

  <section className="section careers anchor-section" id="careers"><div className="shell"><div className="two"><div><div className="section-no">Careers</div><div className="heading"><h2>Do excellent work, with people who understand it.</h2><p>We are building a network of values-led healthcare professionals who care about clinical quality, patient experience and better pathways.</p></div><div className="career-points"><p>We welcome expressions of interest from sonographers, radiographers, advanced practitioners and other experienced clinicians.</p><p>Flexible evening and weekend opportunities may be available as services develop.</p></div></div><CareerForm/></div></div></section>

  <section className="section contact anchor-section" id="get-in-touch"><div className="shell"><div className="two contact-grid"><div><div className="section-no">Get in touch</div><div className="heading"><h2>Let’s talk about what your service needs.</h2><p>Share your priorities and we’ll arrange an initial conversation with one of the founders.</p></div><div className="contact-detail"><span>Registered office</span><address>Insight Health Partners Ltd<br/>128 City Road<br/>London EC1V 2NX</address><small>Please do not include confidential patient information in your message.</small></div></div><ContactForm/></div></div></section>
</main><Footer/><Reveal/></>}
