import Link from "next/link";
import {Header,Footer,Reveal} from "./components";
import {CareerForm,ContactForm} from "./forms";

const team=[
  ["KB","Khaled Barick","Co-Founder"],
  ["GE","Gareth Evans","Co-Founder"],
  ["MP","Mikesh Patel","Co-Founder"],
  ["ML","Maxence Legout","Co-Founder"]
];

const services=[
  ["01","Community Diagnostic Services","Additional diagnostic capacity designed around local demand, pathways and patient needs."],
  ["02","Radiology Workforce Solutions","Experienced clinicians who integrate with radiology teams and support resilient delivery."],
  ["03","Diagnostic Ultrasound","High-quality musculoskeletal and diagnostic ultrasound delivered by qualified sonographers."],
  ["04","Ultrasound-Guided Procedures","Image-guided injections and procedures delivered by experienced practitioners within robust governance."],
  ["05","Community MSK Services","Assessment, diagnostics, prescribing, procedures and onward management in joined-up community pathways."],
  ["06","Service Transformation","Clinical pathway review, workforce development and practical redesign to improve flow and outcomes."]
];

export default function Home(){return <><Header/><main>
  <section className="hero" id="home"><div className="shell hero-grid"><div><div className="eyebrow">NHS experience. Independent thinking.</div><h1>Partnering with the NHS to deliver outstanding clinical and diagnostic services.</h1><p>Insight Health Partners supports NHS Trusts, Integrated Care Boards, GP Federations, Primary Care Networks and Community Diagnostic Centres through diagnostic, radiology and community healthcare services.</p><div className="actions"><Link className="btn light" href="/#our-services">Explore our services</Link><Link className="text-link" href="/#get-in-touch">Start a conversation →</Link></div></div><div className="ultrasound-visual" role="img" aria-label="Abstract diagnostic ultrasound image placeholder"><div className="scan-label">Diagnostic insight</div><div className="scan-field"><span/><span/><span/></div><strong>Better access.<br/>Better pathways.<br/>Better care.</strong></div></div></section>
  <section className="stats" aria-label="Company statistics"><div className="shell stats-grid">{[["80+","Years of combined NHS experience"],["4","Qualified sonographers"],["Advanced","Practice and consultant-level experience"],["In preparation","CQC registration"]].map(([number,label])=><div className="stat" key={label}><div className="num">{number}</div><p>{label}</p></div>)}</div></section>

  <section className="section anchor-section" id="who-we-are"><div className="shell"><div className="section-no">01 — Who we are</div><div className="heading wide"><h2>Healthcare experience that understands the whole pathway.</h2><p>We are four senior healthcare professionals with more than 80 years of combined NHS experience across musculoskeletal services, radiology, emergency medicine, orthopaedics, rheumatology, primary care and community care.</p></div>
    <div className="team">{team.map(([initials,name,role])=><article className="person reveal" key={name}><div className="portrait" role="img" aria-label={`${name} photograph placeholder`}><span>{initials}</span><small>Photo to follow</small></div><div className="person-copy"><h3>{name}</h3><p>{role}</p><span>Senior clinician and qualified musculoskeletal sonographer.</span><div className="bio-placeholder">Full professional biography to be added.</div></div></article>)}</div>
    <div className="story-grid"><div><div className="section-no">Our story</div><h2>Turning frontline understanding into practical action.</h2></div><div className="prose"><p>We built our careers as senior clinicians and leaders in the NHS, working across MSK services, radiology and connected pathways. We have seen first-hand how long waits, fragmented pathways, limited resources and avoidable hand-offs affect patients, teams and the wider system.</p><p>Insight Health Partners began with a shared decision to contribute differently: combining the clinical standards of experienced NHS practitioners with the flexibility to add capacity, remove friction and build services around the people who use them.</p><p>Our role is not simply to fill gaps. We work alongside local teams to understand demand, strengthen governance, develop people and create sustainable pathways that leave services more resilient.</p></div></div>
    <div className="mission"><div><span>Our mission</span><h2>To make high-quality diagnostic and community healthcare easier to access, more efficient to deliver and better connected for every patient.</h2></div></div>
    <div className="grid three"><article className="card"><h3>Our goals</h3><ul className="check"><li>Reduce waiting times and improve access</li><li>Simplify inefficient patient pathways</li><li>Increase safe diagnostic and procedural capacity</li><li>Support and develop the NHS workforce</li><li>Deliver measurable, sustainable improvement</li></ul></article><article className="card"><h3>How we deliver</h3><ul className="check"><li>Flexible evening and weekend services</li><li>Efficient appointment scheduling</li><li>Pathway review to reduce unnecessary steps</li><li>Experienced autonomous practitioners</li><li>Clear outcomes, audit and continuous learning</li></ul></article><article className="card accent-card"><h3>Professional assurance</h3><p>Our team includes HCPC-registered professionals, CSP members, qualified sonographers, independent prescribers and clinicians experienced in ultrasound-guided procedures.</p><p><strong>CQC registration is in preparation.</strong></p></article></div>
  </div></section>

  <section className="section soft anchor-section" id="our-services"><div className="shell"><div className="section-no">02 — Our services</div><div className="heading wide"><h2>Extra capacity, delivered your way.</h2><p>We offer both insourcing and outsourcing models, shaped around local priorities, governance requirements and patient demand.</p></div><div className="delivery-models"><article><span>Insourcing</span><h3>Additional delivery within your service.</h3><p>Our clinicians work within your facilities and agreed pathways, extending capacity while integrating with local teams, systems and governance.</p></article><article><span>Outsourcing</span><h3>A managed service on your behalf.</h3><p>We provide an agreed service model with clinical leadership, workforce, operational delivery and performance assurance.</p></article></div><div className="grid services-grid">{services.map(([no,title,copy])=><article className="service reveal" key={title}><span>{no}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

  <section className="section careers anchor-section" id="careers"><div className="shell"><div className="two"><div><div className="section-no">03 — Careers</div><div className="heading"><h2>Do excellent work, with people who understand it.</h2><p>We are building a network of values-led healthcare professionals who care about clinical quality, patient experience and better pathways.</p></div><div className="career-points"><p>We welcome expressions of interest from sonographers, radiographers, advanced practitioners and other experienced clinicians.</p><p>Flexible evening and weekend opportunities may be available as services develop.</p></div></div><CareerForm/></div></div></section>

  <section className="section contact anchor-section" id="get-in-touch"><div className="shell"><div className="two contact-grid"><div><div className="section-no">04 — Get in touch</div><div className="heading"><h2>Let’s talk about what your service needs.</h2><p>Share your priorities and we’ll arrange an initial conversation with one of the founders.</p></div><div className="contact-detail"><span>General enquiries</span><a href="mailto:enquiries@insighthealthpartners.co.uk">enquiries@insighthealthpartners.co.uk</a><p>Insight Health Partners Ltd<br/>United Kingdom</p><small>Please do not include confidential patient information.</small></div></div><ContactForm/></div></div></section>
</main><Footer/><Reveal/></>}
